FROM node:16

WORKDIR /app

COPY package*.json .

ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
    else npm install --only=production; \
    fi

COPY . .

COPY config/default.json.sample config/default.json

ENV PORT 8888

EXPOSE $PORT

CMD ["node", "serve.js"]